version: '3.5'

services:
  notes-log:
    build: ./
    command: ./notes-log
    depends_on:
      - mongodb
      - amqp
    environment:
      - DB_URI=mongodb://mongodb
      - DB_USERNAME=root
      - DB_PASSWORD=qwerty
      - DB_DATABASE=admin
      - DB_COLLECTION=logs
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_HOST=noteslog
      - RABBIT_PORT=5672
    networks:
      - app_log

  mongodb:
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
      - MONGODB_DATABASE=admin
    ports:
      - "27017:27017"
    networks:
      - app_log

  amqp:
    restart:  always
    image: rabbitmq:latest
    hostname: noteslog
    ports:
      - "5672:5672"
    networks:
      - app_log

networks:
  app_log:
    name: note_network
    driver: bridge